#!/usr/bin/env python3
"""
gen_accent_remap.py — generate the theme-accent remap stylesheet.

The cockpit hardcodes the brand accent as Tailwind `emerald-*` utilities in
61 component files (~250 refs, 50 distinct variants incl. hover/focus/opacity).
That's why switching theme (emerald→amber) leaves most of the cockpit emerald.

Rather than edit 61 files, we follow the codebase's OWN established pattern
(index.css already remaps text-gray-500/600/700 → theme tokens with !important):
scan every emerald utility in use and emit a CSS rule routing it to the live
`--theme-accent*` vars, preserving each opacity via color-mix. One import, zero
component edits, zero layout risk — and the accent now follows the theme
across the WHOLE cockpit.

Run: python3 scripts/gen_accent_remap.py  → writes src/styles/theme-accent-remap.css
"""
import os, re, subprocess
from collections import OrderedDict

SRC = os.path.join(os.path.dirname(__file__), '..', 'src')
OUT = os.path.join(SRC, 'styles', 'theme-accent-remap.css')

# property → (css-property, theme var). text/border/ring use the BRIGHT accent
# (the lighter brand tone used for text & hairlines); solid backgrounds use the
# base accent (button fills). Opacity variants always color-mix from bright.
PROP = {
    'text':   ('color', '--theme-accent-bright'),
    'bg':     ('background-color', '--theme-accent'),
    'border': ('border-color', '--theme-accent-bright'),
    'ring':   ('--tw-ring-color', '--theme-accent-bright'),
    'fill':   ('fill', '--theme-accent-bright'),
    'stroke': ('stroke', '--theme-accent-bright'),
}

def scan_variants():
    out = subprocess.run(
        ['grep', '-rhoE',
         r'((hover|focus|group-hover|active):)?(text|bg|border|ring|fill|stroke)-emerald-[0-9]+(/[0-9]+)?',
         SRC],
        capture_output=True, text=True).stdout
    return sorted(set(l.strip() for l in out.splitlines() if l.strip()))

VARIANT_RE = re.compile(
    r'^(?:(?P<prefix>hover|focus|group-hover|active):)?'
    r'(?P<prop>text|bg|border|ring|fill|stroke)-emerald-(?P<shade>\d+)(?:/(?P<op>\d+))?$')

def css_escape(cls):
    return cls.replace(':', r'\:').replace('/', r'\/')

def selector(cls, prefix):
    esc = '.' + css_escape(cls)
    if prefix == 'hover':       return esc + ':hover'
    if prefix == 'focus':       return esc + ':focus'
    if prefix == 'active':      return esc + ':active'
    if prefix == 'group-hover': return '.group:hover ' + esc
    return esc

def value(prop, shade, op):
    css_prop, var = PROP[prop]
    # solid background: brighter shades (300/400) read as the bright accent.
    if prop == 'bg' and op is None and int(shade) <= 400:
        var = '--theme-accent-bright'
    if op:
        return css_prop, f'color-mix(in srgb, var({var}) {op}%, transparent)'
    return css_prop, f'var({var})'

def main():
    rules = OrderedDict()
    for cls in scan_variants():
        m = VARIANT_RE.match(cls)
        if not m:
            continue
        prefix = m.group('prefix')
        prop = m.group('prop')
        shade = m.group('shade')
        op = m.group('op')
        css_prop, val = value(prop, shade, op)
        rules[selector(cls, prefix)] = f'{css_prop}: {val} !important;'

    lines = [
        '/* ════════════════════════════════════════════════════════════════',
        '   theme-accent-remap.css — GENERATED by scripts/gen_accent_remap.py',
        '   Do not edit by hand. Routes every hardcoded `emerald-*` accent',
        '   utility used in the cockpit to the live --theme-accent* vars so a',
        '   theme change recolours the WHOLE cockpit, not just the chat.',
        '   Regenerate after adding new emerald utilities: npm run gen:accent',
        '   ════════════════════════════════════════════════════════════════ */',
        '',
    ]
    for sel, decl in rules.items():
        lines.append(f'{sel} {{ {decl} }}')
    lines.append('')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print(f'wrote {OUT} — {len(rules)} remap rules')

if __name__ == '__main__':
    main()
